### ISSUE TITLE
Please provide Typescript typings for this

### ISSUE THREAD

**Issue by kenotron** [mongodb/stitch-js-sdk#112]
I would be highly interested in being able to use this SDK in a type safe manner without resorting to my own abridged and self-maintained typing.

**Comment by edaniels** [comment]
We're working on this for a future release. Please stay tuned.

**Comment by marekpetak** [comment]
Hi, any news on types for Stitch?

**Comment by edaniels** [comment]
We are working on a new 4.0 SDK that will be written in typescript and will provide flow bindings as well! The plan is to release this in a couple of months or so unless it's ready before then. Thanks!

**Comment by marekpetak** [comment]
is there way to access Beta anywhere? Good luck!

**Comment by jsflax** [comment]
Not yet! But we'll be sure to let everyone know once the release goes out.

**Comment by edaniels** [comment]
Betas are published at mongodb-stitch-browser-sdk on npm. Typings should be there as well! We plan on releasing the sdk out of beta very soon.
