### ISSUE TITLE
Ionic Mobile Typescript issue with promise

### ISSUE THREAD

**Issue by phingers** [mongodb/stitch-js-sdk#124]
Cross-posting: [https://github.com/ionic-team/ionic/issues/13459](https://github.com/ionic-team/ionic/issues/13459)

I'm getting this error with the MongoDB Stitch service and trying to import their sample code into my Ionic Application.

```
import { StitchClientFactory } from 'mongodb-stitch';
let appId = 'myappid-from-mongodb';
    const clientPromise = StitchClientFactory.create(appId);
    clientPromise.then(client => {
      const db = client.service('mongodb', 'mongodb-atlas').db('myDBname');
      client.login().then(() =>
        db.collection('Messages').updateOne({owner_id: client.authedId()}, {$set:{number:42}}, {upsert:true})
      ).then(() =>
        db.collection('Messages').find({owner_id: client.authedId()}).limit(100).execute()
      ).then(docs => {
        console.log("Found docs", docs)
        console.log("[MongoDB Stitch] Connected to Stitch")
      }).catch(err => {
        console.error(err)
      });
    });
  }
```
Error is:

> polyfills.js:3 Uncaught TypeError: t.resolve is not a function
> at Object.setNativePromise (polyfills.js:3)
> at L.configurable.L.set (polyfills.js:3)
> at module.exports (bson.js:298)
> at $export (bson.js:106)
> at Object. (bson.js:11113)
> at webpack_require (bson.js:30)
> at Object. (bson.js:8511)
> at webpack_require (bson.js:30)
> at Object. (bson.js:8372)
> at Object. (bson.js:8398)

I appreciate any work arounds or ideas on how to get this working for me in Ionic Mobile Hybrid Framework!

**Comment by edaniels** [comment]
Hey @phingers, I'm taking a look into this now. Looks like it may just be a polyfill issue.

**Comment by edaniels** [comment]
@phingers, I'm unable to determine the issue exactly but it appears `zone.js` is overriding the Promise that `mongodb-stitch` expects to use. I've seen reports of this issue before outside of the Stitch SDK so I'm not sure there's anything we can do to fix it.

This seems relevant however: https://github.com/angular/zone.js/issues/891

**Comment by phingers** [comment]
I have it working in IONIC without the factory by importing 

`<script src="https://s3.amazonaws.com/stitch-sdks/js/library/stable/stitch.min.js"></script>`

into index.html

Then in my TS files, I can do something similar too.

```
let client = new stitch.StitchClient(appId);

		let db = client.service("mongodb", "mongodb-atlas").db("DBNAMEHERE");
    client.login().then(() =>
        db.collection('Messages').updateOne({owner_id: client.authedId()}, {$set:{number:42}}, {upsert:true})
      ).then(() =>
        db.collection('Messages').find({owner_id: client.authedId()})
      ).then(docs => {
        console.log("Found docs", docs)
        console.log("[MongoDB Stitch] Connected to Stitch")
      }).catch(err => {
        console.error(err)
      });
```

Hope it helps someone else until it is patched properly.

**Comment by MiguelGonzalezAravena** [comment]
@girish-fuluskar How did you resolve this? I'm facing the same issue.
