### ISSUE TITLE
Error: $regex requires regular expression

### ISSUE THREAD

**Issue by tenjojeremy** [mongodb/stitch-js-sdk#125]
```javascript
const searchByName = async (data) => {
  let db = await MongoConnect(),
    collection_users = db.collection('users'),
    users

  console.log(data.name)

  let regxName = new RegExp(data.name)

  console.log(regxName)

  try {
    let users = await collection_users.find({ name: { $regex: regxName, $options: 'i' } }).execute()
    console.log(users)
  } catch (error) {
    return error
  }

  return users
}
```

**Comment by edaniels** [comment]
@tenjojeremy, the $regex in your code is actually a relaxed extended JSON regular expression. Can you try passing `{ name: bsonRegex }` where bsonRegex is `BSON.BSONRegExp(pattern)`?

You can get the BSON package from `import { BSON } from 'mongodb-stitch';`

**Comment by tenjojeremy** [comment]
hi @edaniels, I tried it like this:
```javascript
import { BSON } from 'mongodb-stitch'

const searchByName = async (data) => {
  let db = await MongoConnect(),
    collection_users = db.collection('users'),
    users

  console.log(data.name)

  let regxName = new RegExp(data.name)

  console.log(regxName)

  let bsonRegex = BSON.BSONRegExp(regxName, 'i')

  console.log(bsonRegex)

  try {
    users = await collection_users.find({ name: bsonRegex }).execute()
    console.log(users)
    return users
  } catch (error) {
    return error
  }
}
```

I dont get an error now, but instead I am getting all the users even if they dont match the pattern.

**Comment by edaniels** [comment]
What's the pattern? Have you tried the same pattern in the mongo shell?

**Comment by tenjojeremy** [comment]
My pattern is /hay/ and it works in the mongo shell and it still doesent work

```javascript
let bsonRegex = BSON.BSONRegExp('hay', 'i')
```

I get this when I console.log(bsonRegex)

 ```javascript
BSONRegExp {_bsontype: "BSONRegExp", pattern: "", options: ""}
```

**Comment by edaniels** [comment]
Try `let bsonRegex = new BSON.BSONRegExp('hay', 'i')` instead

**Comment by tenjojeremy** [comment]
@edaniels Yes! that worked.

Thank you.

**Comment by edaniels** [comment]
Woo! We'll publish a new SDK with that fix once the change goes in on the BSON library. Have fun developing!

**Comment by richtera** [comment]
I am running into this again. It seems to match none of my records with my regex even though I am passing BSON.BSONRegExp() but I am using the server-sdk. Works fine inside of mongo-shell and when I serialize the whole query using JSON.stringify() it does look correct:
```{ info: new BSON.BSONRegExp("^all:") }``` serializes to ```{ "info": { "pattern": "^all:" } }``` but seems to cause no records being returned. When I do the same query in the shell I get 
```db.my_collection.find({info: {$regex: "^all:" }}).count()``` 2320 records. I am not quite sure at what level this fails.
