### ISSUE TITLE
Question: Control Confirm Password Flow

### ISSUE THREAD

**Issue by saniyusuf** [mongodb/stitch-js-sdk#152]
Is there a way to control the email that is sent when a user is created with the StitchClient. Currently, it sends a string that is a link. This link is very non-readable to real users. Is there any way we can control this and maybe integrate a proper email flow?

**Comment by edaniels** [comment]
At the moment, not currently. You can use something like Auth0 or make a feature request at https://mongodb.canny.io/mongodb-stitch.
