### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by saniyusuf** [mongodb/stitch-js-sdk#155]
Hi Guys,
It seems the new 4.0.7 update doesn't compile well with web pack. I have resorted to the JS SDK again. This is on an Angular 6 application. 

The error is seen below and this is after I try to use the client to initialise the default app client on the Stitch object. 

`vendor.js:64763 Uncaught ReferenceError: Buffer is not defined
    at fnv1a32 (vendor.js:64763)
    at fnv1a24 (vendor.js:64781)
    at vendor.js:64804
    at push../node_modules/bson/dist/bson.js.commonjsGlobal (vendor.js:63504)
    at Object../node_modules/bson/dist/bson.js (vendor.js:63506)
    at __webpack_require__ (runtime.js:82)
    at vendor.js:75550
    at Object../node_modules/mongodb-extjson/dist/mongodb-extjson.js (vendor.js:75552)
    at __webpack_require__ (runtime.js:82)
    at Object../node_modules/mongodb-stitch-core-sdk/dist/esm/auth/internal/CoreStitchAuth.js (vendor.js:78042)`

**Comment by edaniels** [comment]
Hi again, this is an issue with both the bson package we depend on and the angular framework for not polyfilling in node automatically like webpack would. Fixing the former is easier so I'll see what I can do today for that.

**Comment by edaniels** [comment]
@saniyusuf can you try out an alpha build of the SDK at `4.0.8-0`? It is a prerelease build with an `alpha` tag so it's not ready for normal installation. You can do `npm install mongodb-stitch-browser-sdk@alpha`

**Comment by edaniels** [comment]
@saniyusuf the most likely solution here will come from https://github.com/mongodb/stitch-js-sdk/pull/156 and it should just work

**Comment by saniyusuf** [comment]
@edaniels I will stay tuned

**Comment by edaniels** [comment]
@saniyusuf Can you try 4.0.8 for me?

**Comment by saniyusuf** [comment]
@edaniels Let me get back to you on that after I try.

**Comment by saniyusuf** [comment]
@edaniels Crept the 4.0.9 into my build, no more Buffer issues. Also, does this version have the BSON utility or is that still a separate tool?
