### ISSUE TITLE
Stitch Client .find() Projections Not Working For Collections

### ISSUE THREAD

**Issue by saniyusuf** [mongodb/stitch-js-sdk#158]
I am trying to use the projection feature of the .find() function as follows for a collection on mine via Stitch. 

.find(
        { owner_id : someID },
        { "email": 1 }
      )
      .first();

Basically, I want only the email field to be returned. However, no matter what I do the whole document comes back. Interestingly enough, the same is happening when I exclude a field by using 0 instead. The whole document just comes back. 

Is this an expected behaviour due to feature not quite there yet, or is this a bug?

**Comment by edaniels** [comment]
https://s3.amazonaws.com/stitch-sdks/js/docs/4.0.3/interfaces/remotemongocollection.html#find shows that find takes options which you can pass in a projection to under the projection key/field.

**Comment by saniyusuf** [comment]
@edaniels thanks that clear everything up. Cheers
