### ISSUE TITLE
How to retrieve private images from S3?

### ISSUE THREAD

**Issue by enniob** [mongodb/stitch-js-sdk#170]
I'm using the stitch-js-sdk to retrieve some images from my S3 bucket. I can get the list of files in the folder I want, but when I try to view them on my app I'm getting a 403 error (forbidden) since the images are set to private, is possible to view private images with the access key that was created when I setup my stitch app to connect to my S3 account?

Here is the code I have to access my bucket 

```
const aws = this.client.getServiceClient(AwsServiceClient.factory, "myapp");
const args = {
   Bucket: bucketName,
   Prefix: folderName
};

const request = new AwsRequest.Builder()
   .withService('s3')
   .withAction('ListObjects')
   .withArgs(args);

aws.execute(request.build())
   .then(result => {
      console.log(result);
   })
   .catch(err => {
      console.log(err);
   });

```

**Comment by enniob** [comment]
I found the documentation on the AWS on how to generate the i

**Comment by haleyowen** [comment]
Hey @enniob! Thanks for reaching out. So you have a few options.

1. If you’re publicly displaying the images, then just make them public on amazon. If you turn list option off in the permissions on Amazon for those images, then people would need the exact url to view it so it's not like random people on the internet will be going through your photos. So unless it's actually sensitive data, this option might be fine.

2. You can use the GetObject method with the Stitch sdk. This will give you back the base64 version of the image. Then you can either convert it to an image or embed the base64 directly into the `src` of an `<img>` tag in your html which would look something like 
```
<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
    9TXL0Y4OHwAAAABJRU5ErkJggg==" />
```

3. You can sign the GET request with your AccessKeyId and Signature as query parameters. This [link](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth) will show you how to create the signature. 

Hope this helps!
