### ISSUE TITLE
Server sdk not working with aws lambda function

### ISSUE THREAD

**Issue by raza2022** [mongodb/stitch-js-sdk#185]
I am try to use it on lambda function. but it event can't initialize on lambda function. I am sure (at least what I read about doc) that I am doing every configuration right and that same code working on with client sdk on a front end site. 
currently I am just initialize as 
```
exports.handler = function(event, context, callback, overrides) {
  const client = Stitch.initializeDefaultAppClient('my-secret-appname');
```
whenever function invokes it throw error `EROFS: read-only file system, mkdir '/home/sbx_userXXXX'`
after going some more deep into lambda docs I see that Lambda only allows you to write to the **/tmp** directory
so how can I use it with lambda, anyone getting the same error. give me a hint as any help will be greatly appropriated

**Comment by chadokruse** [comment]
I believe you can change the default storage location via the `withDataDirectory` method:

```javascript
const { Stitch, StitchAppClientConfiguration } = require('mongodb-stitch-server-sdk');
 
const client = Stitch.initializeAppClient("<your-client-app-id>", new StitchAppClientConfiguration.Builder().withDataDirectory('/some/path').build());
```

https://www.npmjs.com/package/mongodb-stitch-server-sdk#changing-the-default-data-directory

**Comment by raza2022** [comment]
@chadokruse Thanks :+1:

**Comment by pablocid** [comment]
@chadokruse Thanks !!!!!!!!!!
