### ISSUE TITLE
Natively Support Casting Types

### ISSUE THREAD

**Issue by saniyusuf** [mongodb/stitch-js-sdk#199]
Feature Request::
I was wondering if it is possible to add a way for us to be able to typecast our calls from the client VIA typescript.

**Comment by saniyusuf** [comment]
So say I make a request to the Stitch SDK, I want to be able to cast the return type to a TS Interface so that the returned Array is treated as the module I type cast it to

**Comment by adamchel** [comment]
So actually, for the `RemoteMongoCollection` this is already possible in the SDK, using the `Codec` interface from the SDK and [User-Defined Type Guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) from TypeScript.

You can also cast the result of a Stitch function, though we do not currently support `Codec` with `callFunction`. Let us know if this is something you would find useful!

I wrote a small sample Node.js application that demonstrates this functionality, and I tried to add some comments to help you get started. The application demonstrates having a collection of `CustomObject` that you can directly insert and retrieve using a `Codec`. It also demonstrates casting the result of a Stitch function into a `CustomObject`, but this does not use a `Codec`.

See the sample at https://gist.github.com/adamchel/96bf0d6da268ea252f078a40fce523ec

If you create a Stitch app and configure it correctly (see comments in the sample), you should be able to run the above sample by running:
```
npm init
npm install @types/node
npm install mongodb-stitch-server-sdk
tsc --init
tsc main.ts
node main.js
``` 

Let me know if you have any questions about this approach, or if this doesn't work for your use case.

This is a pretty advanced feature so we haven't gotten around to documenting this, but hopefully this is something we could work on documenting in the future (@cbush take note). We would also welcome members of the community writing about this! If you find this useful in your app, we'd love to hear about in a blog post.
