### ISSUE TITLE
mongodb-stitch-browser-sdk - includes node-fetch lib

### ISSUE THREAD

**Issue by MichaelFBA** [mongodb/stitch-js-sdk#207]
Hello,

I am trying to integrate the mongodb-stitch-browser-sdk into a nativescript vue app.

I am using es imports `import { Stitch, AnonymousCredential } from 'mongodb-stitch-browser-sdk';
` to start building the app and it is throwing an error which looks to be related to the sdk bundling in node-fetch (A node package inside of a browser sdk)

Here is a stacktrace

```
@file:///app/vendor.js:182:14
2   ../node_modules/assert/assert.js@file:///app/vendor.js:490:34
3   __webpack_require__@file:///app/bundle.js:76:34
4   @file:///app/vendor.js:626:33
5   ../node_modules/browserify-zlib/lib/binding.js@file:///app/vendor.js:1040:34
6   __webpack_require__@file:///app/bundle.js:76:34
7   @file:///app/vendor.js:1054:34
8   ../node_modules/browserify-zlib/lib/index.js@file:///app/vendor.js:1666:34
9   __webpack_require__@file:///app/bundle.js:76:34
10  @file:///app/vendor.js:32994:33
11  ../node_modules/node-fetch/lib/index.es.js@file:///app/vendor.js:33190:34
12  __webpack_require__@file:///app/bundle.js:76:34
13  ../node_modules/cross-fetch/dist/node-ponyfill.js@file:///app/vendor.js:8598:36
14  __webpack_require__@file:///app/bundle.js:76:34
15  ../node_modules/mongodb-stitch-core-sdk/dist/esm/internal/net/FetchTransport.js@file:///app/vendor.js:16222:88
16  __webpack_require__@file:///app/bundle.js:76:34
17  ../node_modules/mongodb-stitch-core-sdk/dist/esm/index.js<…>
JavaScript error:
file:///app/vendor.js:182:14: JS ERROR TypeError: util.inherits is not a function. (In 'util.inherits(assert.AssertionError, Error)', 'util.inherits' is an instance of Object)
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: util.inherits is not a function. (In 'util.inherits(assert.AssertionError, Error)', 'util.inherits' is an instance of Object)
at
```

**Comment by MichaelFBA** [comment]
Many Thanks @adamchel 

I'll do as you mentioned. Looking forward to using it :) 👍

**Comment by adamchel** [comment]
We've just released version [4.3.0](https://github.com/mongodb/stitch-js-sdk/releases/tag/v4.3.0), which removes `cross-fetch` as a dependency of the browser SDK, and just uses the `whatwg-fetch` polyfill.

Let us know if this updated version works for you!

**Comment by tkaye407** [comment]
Hi @MichaelFBA. We haven't heard back from you and believe that your issue has been resolved, so we will be closing this ticket.

**Comment by conor909** [comment]
I'm getting this on the latest browser sdk (`^4.3.1`)

**Comment by ExQDev** [comment]
The same error on google cloud functions

**Comment by fabien-h** [comment]
Same error here

`ReferenceError: self is not defined
    at /Volumes/Projects/------/node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
    at /Volumes/Projects/------/node_modules/whatwg-fetch/dist/fetch.umd.js:2:66
    at Object.<anonymous> (/Volumes/Projects/------/node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Volumes/Projects/------/node_modules/mongodb-stitch-browser-core/dist/cjs/core/internal/net/BrowserFetchTransport.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)`

I cannot start to try :(

Would it be possible to do without an SDK ? Just a basic REST API.

**Comment by zenati** [comment]
Same here, same error. Why is this issue closed?
