### ISSUE TITLE
watch method on RemoteMongoCollection in ReactNative

### ISSUE THREAD

**Issue by adrian-gierakowski** [mongodb/stitch-js-sdk#209]
Creating this issue as advised by @adamchel in #23

**Comment by adamchel** [comment]
Hi @adrian-gierakowski thanks for filing this issue.

As per https://github.com/react-native-community/discussions-and-proposals/issues/99, we are planning on contributing support for server-eent events in React Native, which will allow us to implement this without resorting to a hack around `XmlHttpRequest`.

We hope to start work on this in the coming weeks!

**Comment by adrian-gierakowski** [comment]
Hi @adamchel. Has there been any progress on this?

**Comment by adamchel** [comment]
@adrian-gierakowski 

This work got re-prioritized, so I wasn't able to work on it as soon as I would have liked, but I've finally opened a PR on the official React Native repo, so hopefully we will be able to support this soon!

https://github.com/facebook/react-native/pull/25718

**Comment by adrian-gierakowski** [comment]
That's great news @adamchel. Can't wait to try it out.

**Comment by BrianIto** [comment]
Hello Adam! I'm Brian and can't wait to see it working. You did it in a Video in [this link](https://www.youtube.com/watch?v=-OoIpkAxmcw&feature=youtu.be) right?

It was great to the see! Any news please keep us on touch! Thank y'all for your work!

**Comment by adamchel** [comment]
Hey everyone, we've just released experimental `watch` support for React Native! See https://github.com/mongodb/stitch-js-sdk/releases/tag/v4.9.0 for details on how you can use it. We can release this non-experimentally once React Native 0.62 is officially released.

If you have any problems with it, feel free to open a new issue!
