### ISSUE TITLE
Connects per client

### ISSUE THREAD

**Issue by stocksp** [mongodb/stitch-js-sdk#218]
I ported a React-Express-Atlas app to Stitch

I'm seeing a minimum of 2 connections per Stitch client in the Atlas console.
I also see my db tools (NoSqlBooster, MongoChef) generate 2 connections when it attaches directly to Atlas.
Although my clients only have a single global connection to Stitch,  they commonly will generate 4 connections (multiple calls to Stitch for a single page), though the minimum is 2.

Connections  seems to be released after 5 minutes of no queries. 

With a 100 connection maximum (M0, M2 and M5 clusters),  it would appear you can only get a maximum of 25 connections in any 5 minute window.  Your clients (tools or Stitch) will fail to connect  if you reach the 100 connection max. 

Have got this correct?

**Comment by adamchel** [comment]
Hi @stocksp thanks for reaching out.

The database connections you are seeing in the Atlas console are different from connections that exist between your app and Stitch.

When a Stitch client makes an HTTP request to Stitch, it hits a load balancer which might hit one of a dozen or so Stitch servers. Each one of these Stitch servers that you hit may open a pool of database connections, which is what you are seeing in the Atlas console. However, a single Stitch server will reuse a connection if it is getting multiple Stitch client requests for the same app.

What you are likely seeing is that different clients are hitting different Stitch servers behind the load balancer, which makes it appear that each Stitch client opens a database connection. As you make more and more Stitch requests from different clients, some of those requests will start to be on the same Stitch server, thus sharing the connection pool.

Therefore, the limit on the number of Stitch clients you can have should be significantly higher than the limit on the number of database connections you can have with your cluster. 

If you have actually seen an issue where you are not able to open more than 25 Stitch clients in a five minute window, please let us know so we can investigate further.

**Comment by stocksp** [comment]
Adam

There is only one Stitch client (me).  I reverted my app back to Express
and its been a week plus.  The only Stitch client now is the one I launch
on my local machine.
As the Atlas cluster is now communicating with Express the number of
connections is constant at 3, never moves. Until:

I fire up my Stitch branch of the app locally.  I can watch my connections
in the Console.  Mostly 4, always at least 2.  They all go away after 5
minutes of me not doing anything (app not making any Stitch queries). And
they come back if I start using the app.  Absolutely certain it is just my
single local Stitch client that is causing these connections on Atlas.

P:)

**Comment by adamchel** [comment]
Alright, so as I said, those connections make sense, and as you add more Stitch clients, they should start sharing those connections that you see in Atlas. The limit therefore is going to be much higher than 25 connections. Let us know if you have any problems as you scale up!

**Comment by stocksp** [comment]
Thanks for your patience with me.  I'll push it out in a bit ....

**Comment by cicaglisa80** [comment]
Hi all,
I have the same problem as mentioned by stocksp. Every time I open a website my connections go up by 2 not one for some reason. Also I have 120 users not all connected at the same time and I'm already running out of 100 connections on free tier mongo atlas. How is this possible if connections are shared? Do I need to do something in particular on angular side to limit connections to one per client? I thought this was a good solution but at this point I'm worried this will keep becoming a bigger problem if my userbase grows overtime and I can't have at least 200 users per 100 available connections this won't scale... can you please advise/help?

**Comment by adamchel** [comment]
Hi @cicaglisa80, we have some internal improvements currently in development that will reduce the number of connections that the Stitch server makes to MongoDB Atlas, and to clean up stale connections more quickly. These will be rolled out in the coming weeks, and you should then see a reduction in the number of connections being opened.

If you're still having issues in two weeks, please open another GitHub issue so we can investigate further.

**Comment by cicaglisa80** [comment]
Hi adamchel, thanks for the update will keep you posted. Is this going to come as a new release of javascript SDK?

**Comment by adamchel** [comment]
This fix will be on the MongoDB server, so there will be no need to upgrade the JS SDK.

**Comment by cicaglisa80** [comment]
ok great will keep an eye on it

**Comment by matteo-pennisi** [comment]
I am also facing the issue of running out of connections.
I am supposing that the serverless functions that are created in Stitch are backed by AWS Lambda si I tried to apply best practices as documented here: https://docs.atlas.mongodb.com/best-practices-connecting-to-aws-lambda/ but seems impossible to deploy a multifile serverless function from MongoDB Stitch. I need to wait to be fixed on the MongoDB server or the Docs solution will solve the problem?

Thanks in advance

**Comment by adamchel** [comment]
@matteo-pennisi , to clarify, our serverless functions are not backed by AWS Lambda. You can call AWS Lambda functions from Stitch functions (this allows you to call lambda functions from stitch triggers or stitch webhooks as glue code), but we are using our own internal engine for serverless functions.

I'm not sure what exactly you mean by multifile serverless function, but you can call Stitch functions from other stitch functions, and you can even create classes in your Stitch functions and call them from each other.

However, if Stitch doesn't have the functionality you're looking for, you can write your functions in Lambda, and call them from Stitch.

**Comment by adamchel** [comment]
@stocksp @cicaglisa80 over the weekend we released a new version of the Stitch server that should address some of the connections issues you've been seeing. if you still run into issues, please open re-open this issue or open a new one so we can investigate

**Comment by cicaglisa80** [comment]
great thanks will keep an eye on it and give some feedback in coming weeks

**Comment by matteo-pennisi** [comment]
@adamchel Thanks a lot for the explanation and sorry for the mistake. 
I will keep updated if there will be any issues.

**Comment by yfrfelipe** [comment]
I'm facing the same issue and it scary me. Everything is fabulous on Mongodb Stitch, but this issue/feature will make me reconsider Mongodb for my solution. Even if we store the singleton it may cause security issues.

Please let me know how can we limit the number of connections per users. If someone open multiple browser tabs just for fun they'll let my software down.

Thanks in advance,

**Comment by solutegrate** [comment]
I'm having the same issues. Running locally with one user for testing. Once I log in to my app and then pull in documents from a Stitch Function, my connections are 15-20, for just one user. In the future, my app will have 100's of users constantly running Stitch Functions (find,insert,update,deletes, etc.). With the performance I'm seeing right now, this worries me that I'm possibly going to be pounding my head on my desk for choosing this solution and paying WAYY more than what I intended and budgeted based on your pricing model. Please give us some insight on how this is going to affect us longterm and shorterm.

**Comment by yfrfelipe** [comment]
This issue was closed without a valid solution, for me it sounds like a feature, not a bug. I'm right? @solutegrate I think you will be pounding your head on your desk, for sure!

**Comment by FullstackJack** [comment]
Connection limits seem to be a major drawback of using MongoDB with any form of serverless architecture. With the industry moving to cloud functions of various offerings, this should be addressed and restrategized by MongoDB to futureproof the offering. For instance, according to the docs for another popular database offering, (unnamed database) now handles "10,000 writes per second per database (up from 2500) and [unnamed database] supports up to 1 million concurrent connections (up from 100,000)." This is no doubt to support serverless functions and is at no additional charge to users of the unnamed database offering.

Our team ran into the connection limit very quickly when pairing a serverless cloud function offering with MongoDB (yes, we are closing connections after each cloud function request). By running an API stress test with only 100 users, we were able to trigger all database connections to be dropped which caused our cloud function invocations to start failing too.

**In essence, your maximum load for HTTP requests to your serverless backend is proportional to the number of connections you have available to your MongoDB Atlas account.** This means that if you have a hard MongoDB Atlas Connection Limit of 100 and you execute 100 serverless cloud functions outside MongoDB Atlas, you will fill your connection limit and cloud functions will start failing.

Alas, this strategy would probably require MongoDB Inc. to switch to the per write, per read, per delete pricing model to ensure that large installations are charged accordingly with their usage.

**Comment by drewdipalma** [comment]
Hi @FullstackJack – Were you connecting to Atlas to your functions directly or via Stitch? Stitch will act as a bit of a proxy between your Atlas instance and help increase the amount of connections.  As some folks have pointed out above this can lead to higher connection utilization per function/user at the lower end of usage and, while we don't have specific benchmarks for how much this proxying helps at scale, anecdotally it is in the ~2x range (but will vary depending on workload).   Depending on your cluster tier, this can provide well over 100k concurrent connections.  Auto-scaling with Atlas should make moving between tiers a bit more seamless.

**Comment by FullstackJack** [comment]
@drewdipalma After further research, I realized that this problem could be alleviated by not leaning on Cloud Functions so heavily for "all-the-things." We could just migrate our entire suite of HTTPS functions to Google App Engine which in addition to consolidating a mess of individual cloud functions and reducing connections to MongoDB Atlas also has the auto-scaling/auto-healing ninja abilities which allows us to sleep soundly at night.

I looked into Stitch. Not to bash it, but I don't like the package management workflow. Forcing developers to manually manage packages is so 2009. NPM was invented in 2010 and it changed the industry. If you want people to use Stitch, make it more like Google Cloud Functions and Firebase Functions; they provide a very helpful CLI tool that uploads all the source code along with the dependencies from node_modules.

**Comment by yfrfelipe** [comment]
It's frustrating if you have to rely to another solution to mitigate this issue, specially if you use Google Cloud Functions once you can easily integrate with Firebase and have the same results as MongoDB Atlas. This issue was closed, which means that it's not a issue, it's a feature.
