### ISSUE TITLE
Feature Request: watching / opening change streams on entire collections

### ISSUE THREAD

**Issue by boustanihani** [mongodb/stitch-js-sdk#221]
according to: https://docs.mongodb.com/stitch-sdks/js-server/4/interfaces/remotemongocollection.html#watch

**... Please note that this method does not support opening change streams on an entire collection or a specific query. The documents to watch must be explicitly specified by their _id ...**

Will opening change streams on an entire collection be possible in the near future?

**Comment by drewdipalma** [comment]
Hi – We are planning this work, but unfortunately, I can't share a specific timeline at the moment.  If you'd like to track this work more actively, I would recommend adding it as an item to our [Canny board](https://mongodb.canny.io/mongodb-mobile).

**Comment by luskin** [comment]
Any update on this @drewdipalma? We are undergoing a massive refactor moving from Firebase to Mongo and would love to not introduce PubSub into the system to maintain our realtime functionality. As this is going to be a long refactor for our team, is there any updated timeline that might affect our architecture decisions?

**Comment by adamchel** [comment]
Hi @boustanihani and @luskin , with the most recent release of the Stitch JavaScript SDK and the Stitch server, this functionality is now available! You can now call `.watch()` on `RemoteMongoCollection` with no arguments, and it will automatically let a user see all of the change events that they have the permission to see.

If you have any questions or you run into any problems, please open a new issue.

**Comment by phillipmalboeuf** [comment]
@adamchel any updates about the status of `.watch()` in the React Native SDK?

**Comment by KISINGA** [comment]
> Hi @boustanihani and @luskin , with the most recent release of the Stitch JavaScript SDK and the Stitch server, this functionality is now available! You can now call `.watch()` on `RemoteMongoCollection` with no arguments, and it will automatically let a user see all of the change events that they have the permission to see.
> 
> If you have any questions or you run into any problems, please open a new issue.

From the documentation, things should work, but I've not been get started, despite trying everything exactly as stated
When I dug deeper into the code, I found that the browser SDK had only implemented the functionality partially, allowing watch to only work with ids
I'm on the latest SDK, What could I be missing?
![Screenshot from 2019-08-23 15-23-21](https://user-images.githubusercontent.com/9964104/63594116-44308780-c5be-11e9-94b9-bee3ac5fa8b6.png)

**Comment by cbush** [comment]
Hi @KISINGA, are you able to make use of the examples on [this page](https://docs.mongodb.com/stitch/mongodb/watch/)? If not, let me know and I would be happy to try to help more.

**Comment by KISINGA** [comment]
> Hi @KISINGA, are you able to make use of the examples on [this page](https://docs.mongodb.com/stitch/mongodb/watch/)? If not, let me know and I would be happy to try to help more.

Yes, I am
Almost
The problem is that when I pass a $watch object, nothing is ever returned, but when I pass an id it does

**Comment by cbush** [comment]
@KISINGA can you share your $match expression that you're using? One important thing to note is that the $match expression is against the change event itself, not the document that has changed.

**Comment by KISINGA** [comment]
> @KISINGA can you share your $match expression that you're using? One important thing to note is that the $match expression is against the change event itself, not the document that has changed.

[Here](https://gist.github.com/KISINGA/0fec994244228dc47d63a5ebfc32a6d2) is what I was trying

**Comment by cbush** [comment]
Remember that the $match expression is against the [change event](https://docs.mongodb.com/manual/reference/change-events/) itself. That's why you need to refer to `documentKey._id`. Also, remember to instantiate the ObjectId with the `new` keyword. Try this:

```
.watch({"documentKey._id": new BSON.ObjectId(user.id)})
```

**Comment by KISINGA** [comment]
> Remember that the $match expression is against the [change event](https://docs.mongodb.com/manual/reference/change-events/) itself. That's why you need to refer to `documentKey._id`. Also, remember to instantiate the ObjectId with the `new` keyword. Try this:
> 
> ```
> .watch({"documentKey._id": new BSON.ObjectId(user.id)})
> ```

Thanks for the clarification
My mistake was assuming that watch works like a "live query"
The BSON mistake was released and corrected

**Comment by adamchel** [comment]
Glad to hear the issue was resolved. We will look into clarifying the documentation. Feel free to open a new issue if you run into any other problems!
