### ISSUE TITLE
Working With JS-BSON

### ISSUE THREAD

**Issue by saniyusuf** [mongodb/stitch-js-sdk#226]
I want to work with JS-BSON. It seems from the documentation found here [https://docs.mongodb.com/stitch-sdks/js/4/index.html](url), the link says it is bundled as part of the SDK. However, this is not correct. So I tried to just manually add JS-BSON, but no luck with that either. 

What is the correct way to work with JS-BSon while using the stitch client? I want to use it to generate a BSON Object to sear by _id which requires a BSON object.

**Comment by tkaye407** [comment]
Hi Sani, 

Currently, we do bundle BSON in with the Browser SDK. If you are importing the following script: 

` <script src="https://s3.amazonaws.com/stitch-sdks/js/bundles/4/stitch.js"></script>  `

The following code should work: 


```
const stitchClient = stitch.Stitch.initializeDefaultAppClient("APP_ID");

const mongoClient = stitchClient.getServiceClient(
	stitch.RemoteMongoClient.factory, 
	"mongodb-atlas"
);

const itemsCollection = mongoClient.db("store").collection("items");

const filterDoc = {_id: new stitch.BSON.ObjectId("5c6331498b247b872c23d512")};

itemsCollection.find(filterDoc, {limit: 1}).first().then(result => {
	if (result) {
		console.log("Successfully Found Document: " + JSON.stringify(result));
	} else {
		console.log("No matching document found");
	}
}, (error) => {
	alert("Error Finding Document: " + error);
});
```

If this syntax of `new stitch.BSON.ObjectId(object-id)` does not work for you, please let us know.

**Comment by saniyusuf** [comment]
Hi, @tkaye407 So I am using the Stitch Client with Angular. stitch-browser-sdk version 4.1.2 to be specific.

In this version, there actually isn't BSON as an exported member. 
For example, I import stitch as so `import { Stitch, RemoteMongoClient } from "mongodb-stitch-browser-sdk";
`

If you look into what this module "mongodb-stitch-browser-sdk" exports, BSON is not one of the members. 
A look through the file reveals these as the exported members 
`export * from "mongodb-stitch-browser-core";
export * from "mongodb-stitch-browser-services-mongodb-remote";`

If your browse through the "mongodb-stitch-browser-core" member, you will see all sorts like Stitch being exported but nothing about BSON. 

Let me know if this helps.

**Comment by dkaminsky** [comment]
As of newest version 4.2.0 you should be able to grab BSON a an export of the browser SDK, e.g.

`import { Stitch, BSON } from ‘mongodb-stitch-browser-sdk’`

Does this make things easier for you?

**Comment by saniyusuf** [comment]
You are right man. I upgraded to 4.2.0 and it is all good now thank you.

**Comment by tkaye407** [comment]
Glad you got it working. Please feel free to open up another issue should you run into any more problems.
