### ISSUE TITLE
Client to server authentication

### ISSUE THREAD

**Issue by joesamcoke** [mongodb/stitch-js-sdk#236]
I need to use lambda functions. How you go about client to server authentication?

So if the user is logged into stitch in the client then makes a call to the lambda function. I need to validate the user in the lambda function and call other stitch services.

I was thinking to include the client access token in the request to the lambda function then call other stitch services using the access token as the auth header. Would this work and be the best way?

**Comment by drewdipalma** [comment]
Hi – 

You have a couple of options for this workflow and we may be able to give more prescriptive advice if you can add further details about your application.  At a high level, we would recommend:

1. Calling a Stitch Function directly from the SDK, and then calling a lambda function from within the Stitch Function using the [AWS service](https://docs.mongodb.com/stitch/services/aws/#lambda-service) (Returning necessary information).  
2. Calling a lambda function directly from the [SDK](https://docs.mongodb.com/stitch/services/aws/#calling-an-aws-service-from-the-sdks) and then calling a Stitch Function from within Lambda using an SDK or hitting a Stitch Webhook.  

Alternatively, you could construct a more custom flow using the [Stitch SDK API endpoints](https://github.com/mongodb/stitch-specifications/blob/master/source/sdks/sdks.rst), but this may be a bit more complex than your workflow needs.  

Thanks,
Drew

**Comment by tkaye407** [comment]
Hi @joesamcoke, we haven't heard from you in a while so we will be closing this issue. Please let us know if you have any more questions!
