### ISSUE TITLE
Question: is this secure?

### ISSUE THREAD

**Issue by remotealex** [mongodb/stitch-js-sdk#257]
It seems like the only thing you need to get up and running with stitch is the `appId`. Which is super cool, but that Id appears in the source files so presumably anyone who know what to look for could just go and grab that `appId` and create an app to access my data! 

I really hope I've missed something here. Please inform me of how it should be done!

**Comment by remotealex** [comment]
Okay just seen `Allowed Origins` in Stitch settings. Sorry!

**Comment by tkaye407** [comment]
Hi, I apologize we were not able to respond yesterday. Allowed origins are one way to secure your app. But generally, you should use stitch rules to secure access to your data. With properly configured rules it should not be a problem at all to publish your app_id with any allowed request origins.
