### ISSUE TITLE
Intermittent collection watch errors on a stale page

### ISSUE THREAD

**Issue by bibyzan** [mongodb/stitch-js-sdk#280]
I've already discussed this issue with @adamchel, just moving the information here so it isn't lost and can be tracked better.

### My usage of `collection.watch` (returns observable)

```
private users: RemoteMongoCollection<DDUser>;

watchUser(userId: string, getCurrent: boolean = false): Observable<DDUser> {
        return new Observable(observer => {
            this.users.findOne({user_id: userId}).then(userObj => {
                if (getCurrent) {
                    observer.next(userObj);
                }
                const usrStream = this.users.watch([userObj._id]);
                usrStream.then(stream => {
                    stream.onNext(update => observer.next(update.fullDocument));
                    stream.onError(err => observer.error(err));
                    observer.add(() => {
                        // called on unsubscribe
                        stream.close();
                    });
                }).catch(err => observer.error(err));
            }).catch(err => observer.error(err));
        });
    }
```

### The bug

The errors I have listed below are what I get when the `stream.onError` block is hit

This bug is elusive and tricky to reproduce, it typically happens to me when I've had a `collection.watch` stream open on a page before putting my computer to sleep. Then once the computer is resumed and the page is still loaded I will typically see one of the following errors:

```
StitchServiceError
errorCode: 46
errorCodeName: "Unknown"
message: "stream closed: undefined"
name: "StitchServiceError"
```

The above error is the most common, but one time I caught some additional errors preceding this one, not sure if they caused this behavior since I don't see it every time

(This screenshot is in safari, but I get the errors on every browser I've tested)

![Screen Shot 2019-05-15 at 8 56 42 AM](https://user-images.githubusercontent.com/8891774/58651323-ff5ac480-82de-11e9-9e39-63eff44346ea.png)

if I click the link for the last request that said `Failed to load resource: the server responded with a status of 401 ()` most of them also say when you open them in the resources tab (in safari) `failed to resource`. However, on that particular last log, it shows this response in resources:

```
{
    "error": "invalid session",
    "error_code": "InvalidSession",
    "link": "https://stitch.mongodb.com/groups/my-group-id/apps/my-app-id/logs?co_id=5cdb3143bd14439563c8586a"
}
```

Finally, when I checked the networking tab for this session, I had a good log of the errors happening over time. Starting at 17:58:19 GMT - 18:38:39 GMT there are 16 call errors in a row before eventually hitting the `stream` object `onError` with this header:

```
Summary
URL: https://stitch.mongodb.com/api/client/v2.0/app/my-app-id/functions/call?stitch_request=my-request-id
Status: 200
Source: Network

Request
Accept: text/event-stream
Cache-Control: no-cache
Origin: http://localhost:8100
Referer: http://localhost:8100/home
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15
Pragma: no-cache

Response
Access-Control-Allow-Credentials: true
Content-Type: text/event-stream
Access-Control-Expose-Headers: X-Stitch-Location, Location
Access-Control-Allow-Origin: *
Date: Tue, 14 May 2019 18:38:39 GMT
X-Frame-Options: DENY
Content-Encoding: gzip
Cache-Control: no-cache
Vary: Origin
```

A few additional errors I've seen but haven't captured the full errors yet (before file watch gets excited and refreshes my page 🙄)

`The underlying mongodb instance became unavailable` is second most common

Here's a one off error I haven't been able to ever reproduce but I captured:

![Image from iOS](https://user-images.githubusercontent.com/8891774/58650764-8eff7380-82dd-11e9-9e24-f147685836a6.png)

Currently, this bug isn't causing any game breaking issues for my project, but it would be nice to know that eventually it could be eradicated.

### My current workaround to reopen the stream on failure
__(and not endlessly attempt to reopen streams if atlas has hit a connection limit)__

```
subToProfile() {
        let timeRefreshed: Date = null;
        const gotUser = user => {
            this.api.profile = user;
            console.log(user);
            this.gotUser(user);
        };
        this.userWatcher = this.api.db.watchUser(this.api.user.id).subscribe(user => {
            gotUser(user);
        }, err => {
            console.error('watch err', err);
            if (timeRefreshed !== null) {
                const now = new Date();
                const minMinutes = 5;
                if (Math.abs(timeRefreshed.getMinutes() - now.getMinutes()) > minMinutes || timeRefreshed.getDate() !== now.getDate()) {
                    timeRefreshed = new Date();
                    this.userWatcher = this.api.db.watchUser(this.api.user.id).subscribe(user => gotUser(user));
                } else {
                    this.alertCtrl.create({
                        header: 'Your user stream has failed more than twice in the last ${minMinutes} seconds.',
                        subHeader: 'Try refreshing the page to fix',
                        message: err,
                        buttons: [{text: 'Refresh', handler: () => location.reload(true)}, {text: 'Cancel'}]
                    }).then(alert => alert.present());
                }
            } else {
                timeRefreshed = new Date();
                this.userWatcher = this.api.db.watchUser(this.api.user.id).subscribe(user => gotUser(user));
            }
        });
    }
```

## package.json dependencies

```
{
    "@angular/animations": "^7.2.2",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.14",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/pwa": "^0.12.4",
    "@angular/router": "^7.2.2",
    "@angular/service-worker": "^7.2.2",
    "@ionic-native/core": "^5.5.1",
    "@ionic-native/splash-screen": "^5.5.1",
    "@ionic-native/status-bar": "^5.5.1",
    "@ionic/angular": "^4.3.1",
    "@mauron85/cordova-plugin-background-geolocation": "3.0.3",
    "@types/googlemaps": "^3.30.19",
    "cordova-android": "7.1.4",
    "cordova-ios": "4.5.5",
    "cordova-plugin-badge": "0.8.8",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.1.2",
    "cordova-plugin-local-notification": "0.9.0-beta.2",
    "cordova-plugin-mauron85-background-geolocation": "@mauron85/cordova-plugin-background-geolocation@~3.0.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "ionic-angular": "^3.9.5",
    "moment": "^2.24.0",
    "mongodb-stitch-browser-sdk": "^4.3.2",
    "mongodb-stitch-browser-services-aws": "^4.3.2",
    "rxjs": "~6.5.1",
    "zone.js": "~0.9.0"
  }
```

**Comment by adamchel** [comment]
Hi @bibyzan ,

Thanks for the very detailed report. Intermittent failures are to be expected, since the stream requires an uninterrupted connection between Stitch and Atlas, and between Stitch and the browser.

However, we are investigating the cause of the "underlying MongoDB instance became unreachable", since it's occurring more frequently than expected. I'll let you know if we find anything.

**Comment by adamchel** [comment]
Hi @bibyzan,

After an investigation, we determined the most root cause of the "underlying MongoDB instance became unreachable, could not reconnect" error you've been seeing on streams. There was a race condition in the server that would sometimes break change streams when many client streams were opening and closing at the same time.

The error might still occasionally appear, but it should only occur when the underlying MongoDB instance is truly unreachable.

The backend fix should now be released, so please let us know if you are still experiencing this issue.

**Comment by bibyzan** [comment]
I haven't run across this in a while, so I'll go ahead and close this unless it resurfaces
