### ISSUE TITLE
Tokens are stored in browser localStorage

### ISSUE THREAD

**Issue by rvanmil** [mongodb/stitch-js-sdk#286]
I've been working on my first Stitch app which uses Auth0 as a custom authentication provider. This all seems to be working really well, but I did notice that the Stitch browser SDK stores the access and refresh tokens in the browser localStorage.
This is something which is not recommended by Auth0 because it they say it is not secure, [see here](https://auth0.com/docs/security/store-tokens#don-t-store-tokens-in-local-storage).
Are there any plans to change this? Or do you think this is not a security issue?

**Comment by edaniels** [comment]
Hi @rvanmil, we don't believe this to be a security issue. Generally, an issue could come up if there were an [XSS](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)) against your site whereby local storage could be read and exfiltrated. However, in principle, the moment you have an XSS attack, the attacker is free to make requests on your behalf regardless of how authentication material is stored. For that reason, a cookie is also insecure in the same manner. Instead, making sure you are not vulnerable to XSS attacks by auditing your code and making sure your packages are not vulnerable either is a good practice to prevent this.

**Comment by rvanmil** [comment]
Ok, thanks for the clarification!
