### ISSUE TITLE
Stitch user email for Facebook login not updating when Facebook default email is updated

### ISSUE THREAD

**Issue by neonguru** [mongodb/stitch-js-sdk#289]
I sign in to stitch with Facebook and the email gets added to the user data. But if then I go and change the Facebook email on the Facebook site, the stitch user email is not updated - even a week later.

I go to settings in Facebook and look at my apps settings and it shows that my app is getting the new email. But in stitch it is still using the older one.

Is this by design or a defect?
What if a user needs to update their email and still use Facebook to login?

**Comment by adamchel** [comment]
Hi @neonguru , this was originally the intended behavior, but after receiving feedback from users that this doesn't fit the use-case you are describing, we've updated the behavior on the backend server to always update metadata on login if it has changed.

Please feel free to open another issue if you are still experiencing problems or you encounter another issue.

**Comment by neonguru** [comment]
Hi @adamchel , You seem to be saying that the metadata is updated when facebook changes - but this is not the behavior I found or what I am saying is happening with my stitch app. The stitch email address is still, a month later, not updating to match the Facebook email associated with.

I do not have a problem with either behavior at the moment, but would like to know what you guys are doing so I can plan for edge case scenarios.

There is an interesting Facebook page written about this: https://developers.facebook.com/docs/facebook-login/multiple-providers/

They speak about Spotify and Spotify has not updated my email to match the Facebook signin email just like you. If the email stays as it is on first login going forward, then I can count on the email staying the same and match the email of Google or Email logins so that any login type gets them the same data associated to their email, and all emails go to one address.

I just need to know if that is what you will continue to do, counter to what you are saying you are doing.

**Comment by adamchel** [comment]
Hi @neonguru , my mistake. I thought the behavior was changed in the most recent backend server release, but it is actually not going to change until our next release. This should happen toward the end of this week or early next week.

Just to be clear, when this functionality is changed, the email in Stitch will not automatically or immediately change when the email gets changed on the Facebook site. The Stitch email will only fetch the latest email from Facebook when the Stitch client re-authenticates with the Facebook provider. If you have any questions, let me know.

I will update this issue with more information when the behavior is officially changed to automatically update the user metadata when re-authenticating.

**Comment by adamchel** [comment]
Hi again @neonguru . The release with the new behavior should now be deployed. As I mentioned before, this means that the Facebook email metadata of a Stitch user will now be updated whenever that users authenticates to Stitch using the Facebook provider.

Please let us know if you experience any more issues or this is not the behavior you observe.

**Comment by neonguru** [comment]
Thanks you @adamchel . I signed out and signed back in as the facebook user I was testing, and saw that the email is now updated. Thank you for the clarification.
