### ISSUE TITLE
Does MongoDB Stitch React Native SDK support Stitch Mobile Sync (Beta)?

### ISSUE THREAD

**Issue by gajjartejas** [mongodb/stitch-js-sdk#295]
So currently I am using MongoDB Stitch React Native SDK for my new project It would be amazing if it supports offline sync or any other way to link native SDK with react native? So it supports Moblie sync?

**Comment by jsflax** [comment]
Hi Tejas,

Unfortunately, we do not have plans to support mobile sync with react
native at this time. However as an alternative, Realm does offer this
functionality with their react native SDK: https://github.com/realm/realm-js
 https://realm.io/blog/introducing-realm-react-native/

Ar Aoine 19 Iúil 2019 ag 06:44, scríobh Tejas Gajjar <
notifications@github.com>:
