### ISSUE TITLE
Can't register new users anymore

### ISSUE THREAD

**Issue by cicaglisa80** [mongodb/stitch-js-sdk#298]
Since this morning with every new user registration we get the following error:

> POST https://stitch.mongodb.com/api/client/v2.0/app/*****/auth/providers/local-userpass/register 500

Can please someone explain what's going on? Website is live and used to work fine for more than a month now we cna't figure out what has happened this morning.

**Comment by cicaglisa80** [comment]
I just moreved the app Id for security reasons it has our appId

**Comment by adamchel** [comment]
yep, just wanted to make sure. we're looking into it now

**Comment by cicaglisa80** [comment]
thanks

**Comment by adamchel** [comment]
We have identified the root cause of this issue and we plan on deploying a fix later today. I'll update this issue when we do.

**Comment by cicaglisa80** [comment]
Great, just to clarity is this something on your end due to an upgrade?
Also I hope this won't happen in near future again as it took us by surprise this morning...

**Comment by adamchel** [comment]
@cicaglisa80 The backend fix should be deployed. Please let us know if you run into any more problems! And of course. This was something on our backend side that broke when we performed an upgrade.
