### ISSUE TITLE
(Stitch)Error on login when custom user data is enabled

### ISSUE THREAD

**Issue by KISINGA** [mongodb/stitch-js-sdk#339]
I have enabled custom user data according to the [documentation](https://docs.mongodb.com/stitch/users/configure-custom-user-data/)
I have confirmed that the specified Id exists, but on login I get this error:
![Screenshot from 2019-12-06 21-30-20](https://user-images.githubusercontent.com/9964104/70346576-aeb8bb00-186f-11ea-90ee-f9262b17cbe4.png)
I'm on the latest stitch sdk version. Not much info on the error itself, but I'm sure it's something to do with the custom field as renaming the id in the containing document and logging in again get's rid of the error but beats logic

**Comment by KISINGA** [comment]
I guess this was fixed, tested again today without any changes and it worked as intended

**Comment by edaniels** [comment]
@KISINGA sorry I never saw this! Yes we had a bug specifically around our auth callbacks and custom user data. Sorry for the troubles as well as not finding this thread earlier.
