### ISSUE TITLE
Streaming interface

### ISSUE THREAD

**Issue by zacharynevin** [mongodb/stitch-js-sdk#36]
Is it possible to give mongo stitch a streaming interface for mongodb operations? If not, is this something that is planned?

For example:

```
let cursor = db.collection('mycollection').find({})
```

In the native mongodb js library, this would return a cursor in which I can do:
```
cursor.on('data', (datum) => { 
  // do stuff
}
``` 

Thanks so much!

**Comment by edaniels** [comment]
There are plans in the future to do this by having Stitch leverage change streams in MongoDB 3.6. Some basic details about that for just MongoDB are here: http://mongodb.github.io/mongo-java-driver/3.6/driver/tutorials/change-streams/
