### ISSUE TITLE
Skip for `collection.find()`

### ISSUE THREAD

**Issue by zacharynevin** [mongodb/stitch-js-sdk#37]
Hi there,

There doesn't appear to be a way to do pagination on documents in a collection. 

For example, if I do this:
```
this.db.collection('mycollection').find({}).limit(10).skip(5)
```
I get the error: `Uncaught TypeError: this.db.collection(...).find(...).limit is not a function`

**Comment by edaniels** [comment]
Right now we do not support Skip as it discourages index usage. See the bottom of https://docs.mongodb.com/manual/reference/method/cursor.skip/ for some of this reasoning. Range based pagination typically works pretty well as long as you have an exact _id to paginate (skip) upon. Limit should still work by passing it as an option to find (https://mongodb.github.io/stitch-js-sdk/Collection.html#find)
