### ISSUE TITLE
NPM Module not found

### ISSUE THREAD

**Issue by roman2710** [mongodb/stitch-js-sdk#41]
I'm using this `import { StitchClient } from 'mongodb-stitch';` to use mongodb stitch in my nodejs application. I installed it using `npm i -S mongodb-stitch`. But i have an error stating module not found.

**Comment by roman2710** [comment]
Previous v0.0.15 is working

**Comment by mpobrien** [comment]
Apologies for this issue: newly published version (v0.0.28) addresses this.
