### ISSUE TITLE
Update changelog and release notes

### ISSUE THREAD

**Issue by stennie** [mongodb/stitch-js-sdk#68]
It would be helpful to be maintain change history via:
 - [changelog](https://github.com/mongodb/stitch-js-sdk/blob/master/CHANGELOG.md)
 - [releases](https://github.com/mongodb/stitch-js-sdk/releases)

The last entry in the changelog is currently 0.0.11 (2017-06-17) and the current release is v1.1.8.

I appreciate the SDK is evolving rapidly, but there are tools like [`changelog`](https://www.npmjs.com/package/changelog) that can help simplify updating change history based on git commits.

A change history would be extremely useful when trying to work out how to update code examples using older API.

**Comment by edaniels** [comment]
We'll look into this as we come closer to GA.
