### ISSUE TITLE
problem with regex and gridfs

### ISSUE THREAD

**Issue by ShukriChiu** [mongodb/stitch-js-sdk#79]
How can I use a find with regex and get picture from GridFS.

**Comment by edaniels** [comment]
Hi @ShukriChiu, Stitch does not currently support GridFS via the SDK. You can pull the files you need manually although it may not suit your needs. https://docs.mongodb.com/v3.6/core/gridfs/ is  a good reference.

**Comment by jasperSpeicher** [comment]
@edaniels Support for GridFS yet?
