### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by xi-osman** [mongodb/stitch-js-sdk#92]
Can't find demo code on authenticating to Stitch using custom authentication.

**Comment by edaniels** [comment]
Hey @xi-osman, we're actually releasing this soon with https://github.com/mongodb/stitch-js-sdk/pull/91! Stay tuned to that for when you can use it. Feel free to check the code out and give it a try. We should have it next week.

**Comment by edaniels** [comment]
@xi-osman, https://github.com/mongodb/stitch-js-sdk/releases/tag/v2.3.0 contains the changes I mentioned! You can use `client.authenticate('custom', <your_jwt>)` to authenticate

**Comment by xi-osman** [comment]
Got it working but it seems that you have to send the JWT as a property example client.authenticate('custom', { token: 'eyJhbFyPa5wY....' } is this the intended way?

**Comment by edaniels** [comment]
It is not. We will fix that ASAP

**Comment by goatandsheep** [comment]
I don't need a jwt if I'm using Facebook auth, right?
